### PR TITLE
Fix server side apply option

### PR DESCRIPTION
**Pull request by nobuhikosawai**
**SEMVER Update Type:**
- [ ] Major
- [ ] Minor
- [x] Patch

## Description:
Fix typo for the server-side-apply option.
I also enabled server-side apply option in the integration-test.

## Motivation:
Fix a bug in my previous PR https://github.com/CircleCI-Public/kubernetes-orb/pull/42
(Apologies for the typo 😇 )

### CODE REVIEW

**Comment by nobuhikosawai** [comment]
@gmemstr This PR is a fix of my previous PR #42. Could you have a look?

**Comment by nobuhikosawai** [comment]
@gmemstr any thoughts or concerns?

**Comment by spacedroids** [comment]
I'm seeing this output when I run this orb, so I think I am running into the typo - although I can't tell if it is actually fatal to my circleci job. Can someone merge this?

`/bin/bash: line 10: [: missing `]'`

**Comment by gmemstr** [comment]
@nobuhikosawai Would you mind bumping the `xcode` version in `.circleci/config.yml` in this PR so we can get tests running properly? Then I think we're good to go.

**Comment by nobuhikosawai** [comment]
Sure! I see it's updated on master branch so I'll rebase my branch on to it

**Comment by nobuhikosawai** [comment]
@gmemstr It looks like the change I intended was already made and merged by opening the different PR (https://github.com/CircleCI-Public/kubernetes-orb/pull/50). 
This PR only contains the changes to update tests after rebasing on to the master. 

Since the bug is already fixed, I'm okay with this PR to be merged or closed either way!

**Comment by gmemstr** [comment]
@nobuhikosawai Good catch! I didn't see that PR at all - I'll go ahead and close this PR, but thank you for submitting your contribution (if you feel that the integration tests would benefit from having this option enabled, let's go ahead and open a new PR to make that happen)!

**Pull request closed without merging**
