### PR TITLE
[semver:major] Update flags in kubectl

### PR DESCRIPTION
**Pull request by brivu**
- Updated `dry-run` flag to type enum and made default value "none"
- Updated `cascade` flag to type enum and made default value "background"
- Removed deprecated `record` flag

### CODE REVIEW

**Comment by Jaryt** [comment]
as discussed, let's change those strings to enums

**Review by Jaryt — COMMENTED** [review]
lgtm

**Review by Jaryt — APPROVED** [review]

**Comment by tomahawk-pilot** [comment]
can someone expedite this and release soon. production release blocked due to this issue..

**Review by Mateusmsouza — APPROVED** [review]
blz, vlw

**Comment by KyleTryon** [comment]
https://circleci.com/developer/orbs/orb/circleci/kubernetes?version=1.0.0 The change has been published. Thank you to everyone who helped us identify the issues.  You may now update your orb version to `1.0.0`.

Please tell me if you run into any trouble with the new version.

**Pull request merged**
